version: '2'
services:
  web:
    user: "$UID:$GID"
    build: .
    environment:
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
      - BUCKET_NAME=$BUCKET_NAME
    volumes:
     - ./mdbook:/mdbook
    command: >
      bash -c '
      mdbook build -d tmp;
      aws s3 sync tmp s3://$BUCKET_NAME;
      '
